spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          searchPaths: /
          uri: https://github.com/cedarln/springcloud/    #https://github.com/how2j/springcloudconfig/
eureka:
  client:
    serviceUrl:
      defautZone: http://localhost:8761/eureka/