spring:
  application:
    name: config-server
  cloud:
    config:
      lable: master
      server:
        git:
          searchPaths: respo
          uri: https://github.com/how2j/springcloudconfig/
eureka:
  client:
    serviceUrl:
      defautZone: http://localhost:8761/eureka/