#eureka:             #这里的内容放到bootstrap.yml里了
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/   #eureka服务器地址
spring:
  application:
    name: product-view-service-feign  #自己的名称
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:      #thymeleaf默认配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
management: #rabbitMQ
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"