eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #eureka服务器地址
spring:
  application:
    name: product-view-service-ribbon  #自己的名称
  thymeleaf:      #thymeleaf默认配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5