eureka:
  instance:
    hostname: localhost  #主机名称
  client:
    registerWithEureka: false  #不注册到服务器，因为自己就是服务器
    fetchRegistry: false  #不获取服务器的注册信息，因为自己就是服务器
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #本服务器的地址 http://localhost:8761/eureka/

spring:
  application:
    name: eureka-server  #本服务器名称